translation:
 tra_dir:        Translations
#plan was to save as Translations/file.po[t] but po_dir doesn't work :(
#po_dir:         .
 src_lang:       english
 extract_format: sfall

 # FO1@2-specific
 # probably should be in 'ettu' tree but it adds extra dependency (bgforge-config.py can't read anything outside 'translation')

 msg2po_dir: Tools/msg2po

 ettu_gha:    .github/workflows/scripts
 ettu_mods:   Fallout2/Fallout1in2/mods
 ettu_pip:    msgcheck
