name: Pack

on:
 push:
  paths:
  - '.github/workflows/pack.yml'

jobs:

 # https://fodev.net/pastebin/?u=fo1in2-release-list

 Test:
  runs-on: windows-latest
  env:
   MOD_DIR:            "Fallout2/Fallout1in2"
   MOD_RELEASE_NAME:   "Fallout1in2"
   MOD_VERSION_STRING: "FALLOUT ET TU"
   MOD_VERSION_MAJOR:  0
   MOD_ZIP:            "Fallout1in2-v"
  steps:

  - name: Clone
    uses: actions/checkout@master
#   with:
#    fetch-depth: 1

  - name:  Environment
    run:   |
           :
           commits="$(git rev-list HEAD --count)"
           echo ::set-env name=MOD_VERSION_STRING::${MOD_VERSION_STRING} ${MOD_VERSION_MAJOR}.${commits}
           echo ::set-env name=MOD_ZIP::${MOD_ZIP}${MOD_VERSION_MAJOR}.${commits}.zip
           echo ::set-env name=MOD_RELEASE_NAME::${MOD_RELEASE_NAME} v${MOD_VERSION_MAJOR}.${commits}
           echo ::set-env name=MOD_RELEASE_TAG::v${MOD_VERSION_MAJOR}.${commits}
           echo ::set-env name=MOD_RELEASE_DRAFT::true
           echo ::set-env name=MOD_RELEASE_PREPRELEASE::true
           echo ::set-env name=MOD_RELEASE_ZIP:Fallout1in2.zip
    shell: bash

  - name:  Cleanup
    run:   |
           :
           rm -fR $MOD_DIR/Mapper/
           rm -f  $MOD_DIR/ddraw.develop.*
           rm -f  $MOD_DIR/ddraw.fo1in2.ini
           find Fallout2 -name '.gitignore' -delete
           find Fallout2 -name '.gitattributes' -delete
    shell: bash

  - name:  Copy UndatUI
    run:   |
           :
           cp "Tools/Undat UI/undat.exe" $MOD_DIR
           cp "Tools/Undat UI/undat_files.txt" $MOD_DIR
    shell: bash

  - name:  Update configuration
    run:   |
           :
           sed -ri "s!^[\t\ ]*VersionString[\t\ ]*=[\t\ ]*.+!VersionString=$MOD_VERSION_STRING!" $MOD_DIR/ddraw.ini
           grep "^VersionString=" $MOD_DIR/ddraw.ini
           unix2dos $MOD_DIR/*.txt $MOD_DIR/*.ini $MOD_DIR/*.cfg $MOD_DIR/config/*
    shell: bash

  - name:  Pack
    run:   7z a "$GITHUB_WORKSPACE/$MOD_ZIP" -m9=Deflate64 Fallout1in2
    shell: bash
    working-directory: Fallout2

  - name:  Pack listing
    run:   7z l $MOD_ZIP
    shell: bash

  - name: Create release
    id:   release
    uses: actions/create-release@v1
    with:
     tag_name:     ${{ env.MOD_TAG }}
     release_name: Fallout1in2 ${{ env.MOD_TAG }}
     draft:        ${{ env.MOD_RELEASE_DRAFT }}
     prerelease:   ${{ env.MOD_RELEASE_PRERELEASE }}
    env:
     GITHUB_TOKEN: ${{ secrets.ANTALASKAYA_TOKEN }}

  - name: Upload release package
    uses: actions/upload-release-asset@v1.0.1
    with:
     upload_url:         ${{ steps.release.outputs.upload_url }}
     asset_path:         ${{ env.MOD_ZIP }}
     asset_name:         ${{ env.MOD_RELEASE_ZIP }}
     asset_content_type: application/zip
    env:
     GITHUB_TOKEN: ${{ secrets.ANTALASKAYA_TOKEN }}
