name: Pack

on:
 push:
  paths:
  - '.github/workflows/pack.yml'

jobs:

 # https://fodev.net/pastebin/?u=fo1in2-release-list

 Test:
  runs-on: windows-latest
  env:
   MOD_DIR:            "Fallout2/Fallout1in2"
   MOD_VERSION_STRING: "FALLOUT ET TU"
   MOD_VERSION_MAJOR:  0
   MOD_ZIP:            "Fallout1in2-v"
  steps:

  - name: Clone
    uses: actions/checkout@master
#   with:
#    fetch-depth: 1

  - name:  Environment
    run:   |
           :
           commits="$(git rev-list HEAD --count)"
           echo ::set-env name=MOD_VERSION_STRING::${MOD_VERSION_STRING} ${MOD_VERSION_MAJOR}.${commits}
           echo ::set-env name=MOD_ZIP::${MOD_ZIP}${MOD_VERSION_MAJOR}.${commits}.zip
    shell: bash

  - name:  Cleanup
    run:   |
           :
           rm -fR $MOD_DIR/Mapper/
           rm -f  $MOD_DIR/ddraw.develop.*
           rm -f  $MOD_DIR/ddraw.fo1in2.ini
           find Fallout2 -name '.gitignore' -delete
           find Fallout2 -name '.gitattributes' -delete
    shell: bash

  - name:  Copy UndatUI
    run:   |
           :
           cp "Tools/Undat UI/undat.exe" $MOD_DIR
           cp "Tools/Undat UI/undat_files.txt" $MOD_DIR
    shell: bash

  - name:  Update configuration
    run:   |
           :
           sed -ri "s!^[\t\ ]*VersionString[\t\ ]*=[\t\ ]*.+!VersionString=$MOD_VERSION_STRING!" $MOD_DIR/ddraw.ini
           grep "^VersionString=" $MOD_DIR/ddraw.ini
           unix2dos $MOD_DIR/*.txt $MOD_DIR/*.ini $MOD_DIR/*.cfg $MOD_DIR/config/*
    shell: bash

  - name:  Pack
    run:   7z a "$GITHUB_WORKSPACE/$MOD_ZIP" Fallout1in2
    shell: bash
    working-directory: Fallout2

  - name:  Pack listing
    run:   7z l $MOD_ZIP
    shell: bash
