name: Schedule

on:
 schedule:
 - cron: 30 * * * *

jobs:

 sfall-dev:
  runs-on: ubuntu-latest
  env:
   MOD_DIR:            "Fallout2/Fallout1in2"
  steps:

  - name: Clone
    uses: actions/checkout@master
    with:
     token: ${{ secrets.ANTALASKAYA_TOKEN }}
#    fetch-depth: 1

  - name:  ReAttach HEAD
    run:   git checkout $(echo "$GITHUB_REF" | awk -F / '{print $3}')

  - name: Download ddraw.dev.dll
    run:  |
          :
          curl -L "https://ci.appveyor.com/api/projects/rotators/sfall/artifacts/ddraw.dll?job=Configuration:%20ReleaseXP&branch=develop&pr=false" -o $MOD_DIR/ddraw.dev.dll
          echo ::set-env name=SFALL_COMMIT::$(curl -Ls https://ci.appveyor.com/api/projects/rotators/sfall/branch/develop 2>/dev/null | jq -r '.build.commitId')
          git diff --quiet || echo ::set-env name=GHA_COMMIT::true

  - name: Push ddraw.dev.dll
    if:   env.GHA_COMMIT == 'true'
    run:  |
          :
          git config --global user.name  "${{ secrets.ANTALASKAYA_NAME }}"
          git config --global user.email "${{ secrets.ANTALASKAYA_EMAIL }}"
          git commit --all --message="sfall-dev (phobos2077/sfall@${{ SFALL_COMMIT }})" && git push
