name: Scripts

on:
 push:
  paths:
  - '.github/workflows/scripts.yml'
  - '.github/workflows/scripts.compile.sh'
  - 'Fallout2/Fallout1in2/Mapper/source/scripts/**/*.[Ss][Ss][Ll]'
  - 'Fallout2/Fallout1in2/Mapper/source/scripts/**/*.[Hh]'
 pull_request:

jobs:

 Compile:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@master
    with:
     fetch-depth: 1

  - name:  Compile
    run:   .github/workflows/scripts.compile.sh
    shell: bash

 ###

 ReDefine:
  needs:   Compile
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@master
    with:
     fetch-depth: 1

  - name:  ReDefine
    run:   Tools/ReDefine/ReDefine.exe --config Tools/ReDefine/ReDefine.cfg --scripts Fallout2/Fallout1in2/Mapper/source/scripts/ --headers Fallout2/Fallout1in2/Mapper/source/scripts/headers/ --debug-changes >/dev/null
    shell: bash

  - name:  Changes
    run:   cat ReDefine.log | egrep -v '^(Added |Process .+ define)'
    shell: bash

  - name:  Warnings
    run:   test -f ReDefine.WARNING.log && cat ReDefine.WARNING.log
    shell: bash

  - name:  Debug
    run:   test -f ReDefine.DEBUG.log && cat ReDefine.DEBUG.log
    shell: bash

  - name:  Cleanup
    run:   rm ReDefine*.log && git status
    shell: bash

  - name:  Compile
    run:   .github/workflows/scripts.compile.sh
    shell: bash
