name: Scripts

on:
 push:
  paths:
  - '.github/workflows/scripts.yml'
  - '.github/workflows/scripts.compile.sh'
  - 'Fallout2/Fallout1in2/Mapper/source/scripts/**/*.[Ss][Ss][Ll]'
  - 'Fallout2/Fallout1in2/Mapper/source/scripts/**/*.[Hh]'
 pull_request:

jobs:

 Compile:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@master
    with:
     fetch-depth: 1

  - name:  Compile
    run:   .github/workflows/scripts.compile.sh
    shell: bash
