name: Scripts

on:
 push:
  paths:
  - '.github/workflows/scripts.yml'
  - '.github/workflows/scripts.compile.sh'
  - 'Fallout2/Fallout1in2/Mapper/source/scripts/**/*.[Ss][Ss][Ll]'
  - 'Fallout2/Fallout1in2/Mapper/source/scripts/**/*.[Hh]'
  - 'Tools/sFall_ScriptEditor/resources/compile.exe'
  - 'Tools/ReDefine/ReDefine.exe'
  - 'Tools/ReDefine/ReDefine.cfg'
 pull_request:

jobs:

 Compile:
  if: github.actor != 'antalaskaya'
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@master
#   with:
#    fetch-depth: 1

  - name:  Compile
    run:   .github/workflows/scripts.compile.sh
    shell: bash

 ###

 ReDefine:
  needs:   Compile
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@master
#   with:
#    fetch-depth: 1

  - name:  ReDefine
    run:   Tools/ReDefine/ReDefine.exe --config Tools/ReDefine/ReDefine.cfg --scripts Fallout2/Fallout1in2/Mapper/source/scripts/ --headers Fallout2/Fallout1in2/Mapper/source/scripts/headers/ >/dev/null
    shell: bash

  - name:  Changes
    run:   cat ReDefine.log | egrep -v '^(Added |Process .+ define)'
    shell: bash

  - name:  Warnings
    run:   |
           :
           if [ -f ReDefine.WARNING.log ]; then
              cat ReDefine.WARNING.log
           fi
    shell: bash

  - name:  Debug
    run:   |
           :
           if [ -f ReDefine.DEBUG.log ]; then
              cat ReDefine.DEBUG.log
           fi
    shell: bash

  - name:  Cleanup
    run:   rm ReDefine*.log && git status
    shell: bash

  - name:  Compile
    run:   .github/workflows/scripts.compile.sh
    shell: bash
