name: Text

on:
 push:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'
  - 'Tools/ScanMsg/scanmsg.exe'
 pull_request:

jobs:

 ScanMsg:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@master
#   with:
#    fetch-depth: 1

  - name:  ScanMsg
    run:   |
           :
           $GITHUB_WORKSPACE/Tools/ScanMsg/scanmsg.exe >/dev/null
           if [ -f "scanmsg.txt" ]; then
              cat "scanmsg.txt"
              exit 1
           else
              exit 0
           fi
    shell: bash
    working-directory: Fallout2/Fallout1in2
