name: Text

on:
 push:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'
 pull_request:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'

defaults:
 run:
  shell: bash

jobs:
 All:
  if:      github.actor != 'antalaskaya' && github.ref == 'refs/heads/master'
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: ScanMsg
    uses: wipe2238/ScanMsg@master
    with:
     workdir: Fallout2/Fallout1in2/mods/

 English:
  if:      github.actor != 'antalaskaya' && (github.ref == 'refs/heads/fo1_french' || github.ref == 'refs/heads/fo1_german')
  runs-on: windows-latest
  env:
   MODS_LIST:      fo1_robodog ShowLootWeight
  outputs:
   fo1_robodog:    ${{ steps.config.outputs.fo1_robodog }}
   ShowLootWeight: ${{ steps.config.outputs.ShowLootWeight }}

  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: Config
    id:   config
    run: |
         :
         for dir in ${{ env.MODS_LIST }}; do
             if [[ -d "Fallout2/Fallout1in2/mods/$dir/" ]]; then
                echo "::set-output name=$dir::true"
             fi
         done

  - name: Base
    uses: wipe2238/ScanMsg@master
    with:
     path:    fo1_base/text/english/
     workdir: Fallout2/Fallout1in2/mods/

  - name: Robodog
    if:   steps.config.outputs.fo1_robodog == 'true'
    uses: wipe2238/ScanMsg@master
    with:
     path:    fo1_robodog/text/english/
     workdir: Fallout2/Fallout1in2/mods/

  - name: ShowLootWeight
    if:   steps.config.outputs.ShowLootWeight == 'true'
    uses: wipe2238/ScanMsg@master
    with:
     path:    ShowLootWeight/text/english/
     workdir: Fallout2/Fallout1in2/mods/

 French:
  if:      github.actor != 'antalaskaya' && github.ref == 'refs/heads/fo1_french'
  needs:   English
  runs-on: windows-latest

  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: Base
    uses: wipe2238/ScanMsg@master
    with:
     path:         fo1_base/text/english/
     translations: fo1_french/text/french/
     workdir:      Fallout2/Fallout1in2/mods/

  - name: Robodog
    if:   needs.English.outputs.fo1_robodog == 'true'
    uses: wipe2238/ScanMsg@master
    with:
     path:         fo1_robodog/text/english/
     translations: fo1_robodog/text/french//
     workdir:      Fallout2/Fallout1in2/mods/

  - name: ShowLootWeight
    if:   needs.English.outputs.ShowLootWeight == 'true'
    uses: wipe2238/ScanMsg@master
    with:
     path:         ShowLootWeight/text/english/
     translations: ShowLootWeight/text/french//
     workdir:      Fallout2/Fallout1in2/mods/

 German:
  if:      github.actor != 'antalaskaya' && github.ref == 'refs/heads/fo1_german'
  needs:   English
  runs-on: windows-latest

  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: Base
    uses: wipe2238/ScanMsg@master
    with:
     path:         fo1_base/text/english/
     translations: fo1_german/text/german/
     workdir:      Fallout2/Fallout1in2/mods/

  - name: Robodog
    if:   needs.English.outputs.fo1_robodog == 'true'
    uses: wipe2238/ScanMsg@master
    with:
     path:         fo1_robodog/text/english/
     translations: fo1_robodog/text/german/
     workdir:      Fallout2/Fallout1in2/mods/

  - name: ShowLootWeight
    if:   needs.English.outputs.ShowLootWeight == 'true'
    uses: wipe2238/ScanMsg@master
    with:
     path:         ShowLootWeight/text/english/
     translations: ShowLootWeight/text/german/
     workdir:      Fallout2/Fallout1in2/mods/
