name: Text

on:
 push:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'
  - 'Tools/ScanMsg/ScanMsg.exe'
 pull_request:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'
  - 'Tools/ScanMsg/ScanMsg.exe'

defaults:
 run:
  shell: bash

jobs:

 ScanMsg:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: ScanMsg (local)
    uses: wipe2238/ScanMsg@master
    with:
     executable: Tools/ScanMsg/ScanMsg.exe
     workdir:    Fallout2/Fallout1in2/mods/

  - name: ScanMsg (upstream)
    uses: wipe2238/ScanMsg@master
    with:
     workdir:    Fallout2/Fallout1in2/mods/
