name: Text

on:
 push:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/mods/fo1_base/text/english/**/*.[Mm][Ss][Gg]'
  - 'Tools/ScanMsg/scanmsg.exe'
 pull_request:

jobs:

 ScanMsg:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@master
    with:
     fetch-depth: 1

  - name:  ScanMsg
    run:   |
           :
           $GITHUB_WORKSPACE/Tools/ScanMsg/scanmsg.exe >/dev/null
           test -f scanmsg.txt && cat scanmsg.txt
    shell: bash
    working-directory: Fallout/Fallout1in2/mods/fo1_base/text/english
