name: Text

on:
 push:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'
  - 'Tools/ScanMsg/ScanMsg.exe'
 pull_request:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'
  - 'Tools/ScanMsg/ScanMsg.exe'

defaults:
 run:
  shell: bash

jobs:

 ScanMsg:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: ScanMsg
    run:  |
          :
          $GITHUB_WORKSPACE/Tools/ScanMsg/ScanMsg.exe >/dev/null
          if [ -f "ScanMsg.log" ]; then
             cat "ScanMsg.log"
             exit 1
          else
             exit 0
          fi
    working-directory: Fallout2/Fallout1in2
