name: Tools

on:
 push:
  paths:
  - '.github/workflows/tools.undatui.yml'
  - 'Tools/UndatUI/src/**'

env:
 DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

 UndatUI:
  runs-on: windows-latest
  steps:

  - uses: actions/checkout@v2-beta

  - run:   |
           :
           curl -sL https://github.com/microsoft/vswhere/releases/latest/download/vswhere.exe -o $HOME/vswhere.exe
           "$($HOME/vswhere.exe -latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe)" Tools/UndatUI/src/undat.sln -p:Configuration=Release
    shell: bash
